package main

import "os"
import "fmt"
import "mapreduce"

import ("unicode"
	 "strings"
	 "strconv"
	 )


import "container/list"

// our simplified version of MapReduce does not supply a
// key to the Map function, as in the paper; only a value,
// which is a part of the input file content. the return
// value should be a list of key/value pairs, each represented
// by a mapreduce.KeyValue.
func Map(value string) *list.List {
	// Your Map() will be passed some of the text from the file; 
	// it should split it into words, 
	// and return a list.List of key/value pairs, of type mapreduce.KeyValue.

	// Hint: you can use strings.FieldsFunc to split a string into components.
	f := func(c rune) bool {
		return !unicode.IsLetter(c) //&& !unicode.IsNumber(c)
	}

	words := strings.FieldsFunc(value, f)

	l := list.New()
	for _, word := range words {
		kv := mapreduce.KeyValue{Key: word, Value: "1"}
		l.PushBack(kv)
	}

	return l

}

// called once for each key generated by Map, with a list
// of that key's string value. should return a single
// output value for that key.
func Reduce(key string, values *list.List) string {
	// Your Reduce() will be called once for each key, 
	// with a list of all the values generated by Map() for that key; 
	// it should return a single output value.
	
	count := 0
	for e := values.Front(); e != nil; e = e.Next() {
		v := e.Value.(string)
		ithCount, _ := strconv.Atoi(v)
		count += ithCount
	}

	return strconv.Itoa(count)

}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master x.txt sequential)
// 2) Master (e.g., go run wc.go master x.txt localhost:7777)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) != 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		if os.Args[3] == "sequential" {
			mapreduce.RunSingle(5, 3, os.Args[2], Map, Reduce)
		} else {
			mr := mapreduce.MakeMapReduce(5, 3, os.Args[2], os.Args[3])
			// Wait until MR is done
			<-mr.DoneChannel
		}
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], Map, Reduce, 100)
	}
}
